# Build settings
[build]
  command = "npm run build"
  publish = ".next"

# Build environment variables
[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_DISABLE_SOURCEMAPS = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  # Supabase environment variables
  NEXT_PUBLIC_SUPABASE_URL = "https://wdjmkejewswmklcjyepk.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkam1rZWpld3N3bWtsY2p5ZXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzM0NzIsImV4cCI6MjA2MDkwOTQ3Mn0.RqynIDMUQq0Phx_3A2DpES7FakN7e5DLQl4WV4DJFCs"

# Plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Custom 404 handling
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
